---
title: "Chapter2"
author: "AndreyPovaliy"
date: "2023-09-29"
output: html_document
editor_options: 
  markdown: 
    wrap: sentence
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ГЛАВА 2. МАТРИАЛЫ И МЕТОДЫ

В настоящей главее буду подробно представлены данные о дизайне исследования, подробное описание преддиагностического этапа, описания используемых диагностических методов, регистрируемых данных и классификаторов,

## 2.1 Общая характеристика исследования Исследование можно характеризовать как клиническое исследование диагностических аспектов раннней диагностики рака молочной железы.

Обектом исследования являются новобразования молочной железы, регистрируемые при дигностике с использованием ручного ультразвукого исследования (УЗИ), маммографии (ММГ) и автоматизированного объемного УЗИ сканирования молочных желез (ABUS).
Предметом исследования является изучение диагностической эффективности автоматизированного объемного УЗИ сканирования молочных желез, а также анализ наиболее важных факторов как преддиагностическом этапе, так и при выполнении конкретного диагностического метода, в частности при выполнении автоматизированного объемного УЗИ сканирования молочных желез.
Дизайн исследования можно охарактеризовать ретро-проспективное наблюдательное исследование.
Протокол настоящего исследования был одобрен на заседании локального этического комитета СЗГМУ им.
Мечникова №00 от ХХ.ХХ.ХХХХ года.

Всего в исследование вошло 2794 пациенток. Критерии включения были пациенты женского пола в возрасте от 18 до 80 лет; женщина, посетившая врача
для обследования рака молочной железы, с отсутствием видимых признаков рака молочной железы.
Критериями исключения были: женщины, которые были беременны, кормили грудью или планировали забеременеть; оперативное лечение в анамнезе (лампэктомия, мастэктомия, увеличение груди), Эксцизионная или чрескожная биопсия за последние 12 месяцев,пациентки получавшие лечение по поводу рака молочных желез за последние 12 месяцев. В это исследование была включена одна медицинская клиника- СМТ, состоящая из двух
зданий -амбулаторно-поликлического комплекса и хирургического корпуса со стационаром. Все женщины из амбулаторного отделения были
приглашены для участия в нашем исследовании, участники подписали форму информированного согласия. Все обследования были проведены медицинским персоналом с соответствующей квалификацией. Всем провели клинический осмотр, пальпацию, собрали информацию о социально-демографических данных и потенциальных факторах риска РМЖ.

Все пациентки были разделены на 2 независимые друг от друга выборки по принципу возраста: выборка пациенток с возрастом до 40 лет и выборка пациенток с возрастом от 40 лет включительно.
Принцип разделения по возрасту был связан с различными принципами использования диагностических методов в скрининге рака молочной железы.
У пациенток моложе 40 лет ММГ менее эффективна, так как низкая чувствительность метода и основным методом диагности используется УЗИ метод [@mandelson2000breast].
У пациенток моложе от 40 лет метод ММГ является обязательным в скрининге РМЖ [@narayan2020].
Более подробно об используемых методах можно прочитать в разделе "2.3 Описание диагностических методов".

В выборку до 40 лет вошло 1511 пацинеток.
Эта выборка пациенток была разделена на две группы A и B.
В группу A вошло 724 пациенток и в это группе скрининг проводился с использовонием мануальной УЗИ диагностики и и автоматизированного объемного УЗИ сканирования молочных желез (исследуемая группа).
В группу B вошло 787 пациенток и в этой группе скрининг проводился только с исползовонием ручного УЗИ диагностики (котнтрольная группа).
В выборку 40 лет и старше вошло 1283 пацинеток.
Эта выборка пациенток была разделена на две группы С и D.
В группу С вошло 655 пациенток и в это группе скрининг проводился с использовонием ручного УЗИ, маммографии и автоматизированного объемного УЗИ сканирования молочных желез (исследуемая группа).
В группу D вошло 628 пациенток и в этой группе скрининг проводился только с исползовонием ручного УЗИ и маммографии (котнтрольная группа).
Подробное описание выборок и групп представлено в разделе "2.5 Описание исследуемых групп".
Включение указанного количества пациенток в группы было основано на расчете мощности, более подробно можно прочитать в разделе "2.6 Статистический анализ данных".

Диагностический этап, где проводилась непосредственно диагностическое исследование с использованием методом ручного УЗИ исследования, маммографии и автоматизированного объемного УЗИ сканирования молочных желез в зависимости от группы распределения.

Ппроизводился сбор данных для последующего выления наиболее значимых факторов, а также выявления эффективности изучаемых методов и прогностической ценности метода.



## 2.2 Описание диагностических методов

### 2.2.1 Ручное УЗИ исследование

HHUS выполняли два врача ультразвуковой диагностики со стажем работы более 7 лет. Исследование проводилось в положении лежа, с руками за головой, с последовательным сканированием каждого квадранта обеих молочных железе в сагитальной и аксиальной плоскостях, с исследованием ретроареолярной области и аксиллярных областей с двух сторон. Устройства, используемые для проведения HHUS включали GE LOGIQS 8 (GE Medical Systems, Милуоки, Висконсин, США), Toshiba Aplio 300(Canon Япония)- ультразвуковые системы экспертного класса.

### 2.3.2 Автоматизированное объемное УЗИ сканирование молочных желез (ABUS)

D-автоматизированная ультразвуковая система Invenia (ABUS) оцениваемая в данном исследовании, производства GE Healthcare (Саннивейл, Калифорния, США) 2018 года выпуска--- это компьютерная система для оценки плотной молочной железы.

Каждая молочная железа была визуализирована в трех проекциях: боковой (LAT), переднезадней (AP).и медиальный (MED) с автоматическим датчиком с линейной матрицей от 6 до 14 МГц, прикрепленным к жесткой компрессионной пластине.(площадь 15,4×17,0×5,0 см).Индивидуальная мембрана для датчика была использована для каждой пациентки.
Во время исследования система получала до 300 2D-срезов и реконструировала их в коронарной плоскости.
Стандартизированный процесс осмотра включает использование запатентованной коронарной плоскости для быстрой навигации по молочной железе, а также использование «режима обзора», позволяющего врачу быстро интерпретировать изображения.
Время сбора данных для каждой проекции составляло 60 с, примерно по 3--4 мин на каждую молочную железу.
Обследование проводили в положении лежа.
Полотенце было помещено под плечом, что помогло расправить ткань молочной железы равномерно, соском к потолку.
На молочные железы равномерно наносили гипоаллергенный ультразвуковой гель с дополнительным количество на область соска..
Возможно применение трех уровней компрессии датчика для исследования молочных желез для получения наилучшей визуализации с учетом комфорта пациента.

Сканирование ABUS было непрерывным и автоматизированным.В течение исследования женщин попросили не двигаться, не разговаривать и дышать ровно.
Выполнял исследование сертифицированный персонал со средним медицинским образованием.
После завершения сбора данных ультразвуковой системой весь массив передавался на специальную рабочую станцию для интерпретации.
Оценку изображений ABUS выполнял один врач ультразвуковой диагностики, со стажем работы более 7 лет.
Общее время, необходимое для подготовки пациента и получения ABUS, фиксировалось, в каждом случае и варьировалось примерно между 10 и 15 мин.

### 2.3.3 Маммография
Пациентки старше 40 лет прошли двухпроекционную цифровую маммографию (в медиалатеральной косой и краниокаудальной проекции)обеих молочных желез.
Маммографию также выполняли женщинам моложе 40 лет в случае положительного семейного или личного анамнеза - рак молочной железы. Использумемое оборудование- Planmed Clarity 3D с функцией томосинтеза (Финляндия). Оценку изображений проводил один рентгенолог со стажем работы более 10 лет.
### 2.3.4 Магнитно-резонанская томография

### 2.3.5 Оценка выявленных изменений.

Результаты выявленных изменений были классифицированы по BI-RADS отсортированы по шести категориям [@spak2017]: 0 = неполные данные , 1 = нормальные, 2 = доброкачественные, 3 =вероятно доброкачественные, 4 = подозрительные, 5 = с высокой степенью вероятности злокачественные, для HHUS, ABUS и MG.
Для категории Birads 3 обязательно проводилась магнитно-резонансная томография (МРТ) для выявления истинно отрицательных и ложноотрицательных результатов.
Женщинам, отнесенным к категории 4 или 5, проводилась трепан биопсия под уз-наведением или стереотаксическим наведением с последующей морфологической и при необходимости иммуногистохимической верификацией.

## 2.4 Описание регистрируемых данных и их классификаторв

## 2.5 Описание исследуемых групп

### 2.5.1 Общее описание выборки пациенток до 40 лет

С февраля 2019 по май 2023 года было исследовано 1511 пациенток с возрастом до 40 лет.

Медиана возраста пациенток выборке до 40 лет составила 35 [Q1-Q3: 32;37] лет.
 Минимальный возраст составил 20 лет. Максимальный возраст составил 39 лет. Медиана роста пациенток выборке до 40 лет составил 167 [Q1-Q3: 164;170] см. Медиана веса пациенток выборке до 40 лет составил 59 [Q1-Q3: 55;65] кг.

В выборке до 40 лет были поставлены следующие диагнозы при первичном осмотре: «Без патологии» было 29.91% пациенток(452/1511 случаев) [95% ДИ 0.28;0.32], «Рак» был поставлен в 0.79% (12/1511 случаев) [95% ДИ 0;0.01], «Фиброаденома» была поставлена в 19.99% (302/1511 случаев) [95% ДИ 0.18;0.22], «Фиброзно-кистозная болезнь» в 25.61% (387/1511 случаев) [95% ДИ 0.23;0.28], «Киста» была в 6.42% (97/1511 случаев) [95% ДИ 0.05;0.08], «Листовидная опухоль» - 0.6% (9/1511 случаев) [95% ДИ 0;0.01], «Внутрипротоковая папиллома» - 0.4% (6/1511 случаев) [95% ДИ 0;0.01], «Гиперплазия» было 0.4% (6/1511 случаев) [95% ДИ 0;0.01], «Диффузный фиброаденоматоз» - 15.42% (233/1511 случаев) [95% ДИ 0.14;0.17] и «Локализованный фиброаденоматоз» - 0.46% (7/1511 случаев) [95% ДИ 0;0.01].

Были выялены следующие жалобы: «выделения из соска» было 0.66% (10/1511 случаев) [95% ДИ 0;0.01], боль была в 5.03% (76/1511 случаев) [95% ДИ 0.04;0.06], 
«уплотнение» было в 9.4% (142/1511 случаев) [95% ДИ 0.08;0.11] и не было жалоб в 84.91% (1283/1511 случаев) [95% ДИ 0.83;0.87].

Репродуктивный возраст был в 96.96% (1465/1511 случаев) [95% ДИ 0.96;0.98],  пременопауза была в 3.04% (46/1511 случаев) [95% ДИ 0.02;0.04].

Операций на молочной железе в анамнезе не было в 98.41% (1487/1511 случаев) [95% ДИ 0.98;0.99] и были в 1.59% (24/1511 случаев) [95% ДИ 0.01;0.02] .

В выборке до 40 лет прием гормональных препаратов был в 21.05% (310/1511 случаев) [95% ДИ 0.19;0.23] и не отмечался в 8.95% (1163/1511 случаев) [95% ДИ 0.75;0.79].

В выборке до 40 лет генетическая предрасположенность нет было в 68.57% (1023/1511 случаев) [95% ДИ 0.65;0.7], в то время как предрасположенность отмечалась в 31.43% (469/1511 случаев) [95% ДИ 0.29;0.33].

Была выявлена мутация BRCA BRCA1 было 0.4% (6/1511 случаев) [95% ДИ 0;0.01], мутаций BRCA не выявлено было 1.19% (18/1511 случаев) [95% ДИ 0.01;0.02]. В остальных случаях исследования мутаций не проводилось.

Сторона поражения при осмотре была правая в 11.25% (170/1511 случаев) [95% ДИ 0.1;0.13], левая в 6.55% (99/1511 случаев) [95% ДИ 0.05;0.08], поражения обеих сторон в 3.97% (60/1511 случаев) [95% ДИ 0.03;0.05], в остальных случаях образование не пальпировало - 78.23% (1182/1511 случаев) [95% ДИ 0.76;0.8].

Кожные симптомы при осмотре нет было во всех 100% (1511/1511 случаев) [95% ДИ 1;1].

В выборке до 40 лет втягивание соска при осмотре не было в 98.81% (1493/1511 случаев) [95% ДИ 0.98;0.99], было отмечено в 1.19% (18/1511 случаев) [95% ДИ 0.01;0.02].

Выделения из соска при осмотре не было в 99.54% (1504/1511 случаев) [95% ДИ 0.99;1]., кровянистые выделения были в 0.46% (7/1511 случаев) [95% ДИ 0;0.01].

Тип плотности по ACR при осмотре был «С» в 70.11% (1046/1511 случаев) [95% ДИ 0.67;0.72], тип «D» был в 29.89% (446/1511 случаев) [95% ДИ 0.27;0.32].

Квадрант локализации верхне-нараружный был в 8.01% (121/1511 случаев) [95% ДИ 0.07;0.1], верхне-внутренний - 3.97% (60/1511 случаев) [95% ДИ 0.03;0.05], нижне-наружный - 2.38% (36/1511 случаев) [95% ДИ 0.02;0.03], нижне-внутренний было в 1.19% (18/1511 случаев) [95% ДИ 0.01;0.02], граница внутреннего - 1.72% (26/1511 случаев) [95% ДИ 0.01;0.03], граница наружного - 1.19% (18/1511 случаев) [95% ДИ 0.01;0.02], граница верхнего - 2.91% (44/1511 случаев) [95% ДИ 0.02;0.04], граница нижних - 0.86% (13/1511 случаев) [95% ДИ 0;0.02], вся железа - 0.4% (6/1511 случаев) [95% ДИ 0;0.01].

### 2.5.2 Общее описание выборки пациенток 40 лет и старше
С февраля 2019 по май 2023 года было исследовано 1283 пациенток с возрастом 40 лет и старше.


Медиана возраста пациенток выборке после 40 лет составил 49 [Q1-Q3: 45;56] лет.
Минимальный возраст составил 40 лет. Максимальный возраст составил 79 лет. Медиана роста пациенток выборке после 40 лет составил 166 [Q1-Q3: 164;168] см. Медиана веса пациенток выборке после 40 лет составил 65 [Q1-Q3: 60;73.25] кг. В выборке после 40 лет были поставлены диагнозы Без патологии было 5.61% (72/1283 случаев) [95% ДИ 0.04;0.07].

В выборке 40 лет и старше были поставлены диагнозы при первичном осмотре: «Рак» было 3.51% (45/1283 случаев) [95% ДИ 0.03;0.05], «Фиброаденома» в 10.05% (129/1283 случаев) [95% ДИ 0.08;0.12], «Фиброзно-кистозная болезнь» - 31.57% (405/1283 случаев) [95% ДИ 0.29;0.34], «Киста» было 2.96% (38/1283 случаев) [95% ДИ 0.02;0.04], «Листовидная опухоль» было 1.71% (22/1283 случаев) [95% ДИ 0.01;0.03], "Диффузный фиброаденоматоз" - 41.86% (537/1283 случаев) [95% ДИ 0.39;0.45], «Локализованный фиброаденоматоз» был в 2.49% (32/1283 случаев) [95% ДИ 0.02;0.04], «Мастит» был в 0.23% (3/1283 случаев) [95% ДИ 0;0.01].

Были выявлены следующие жалобы: выделения из соска было в 0.47% (6/1283 случаев) [95% ДИ 0;0.01], боль была в 4.13% (53/1283 случаев) [95% ДИ 0.03;0.05], уплотнение было в 14.34% (184/1283 случаев) [95% ДИ 0.12;0.16], жалоб не было  в 81.06% (1040/1283 случаев) [95% ДИ 0.79;0.83].


Репродуктивный возраст был в 22.37% (287/1283 случаев) [95% ДИ 0.2;0.25], менопауза до 5 лет была в 18.47% (237/1283 случаев) [95% ДИ 0.16;0.21], менопауза более 5 лет была в 24.94% (320/1283 случаев) [95% ДИ 0.23;0.27], пременопауза - 33.9% (435/1283 случаев) [95% ДИ 0.31;0.37], оперативная менопауза - 0.31% (4/1283 случаев) [95% ДИ 0;0.01].


В выборке после 40 лет операций на молочной железе в анамнезе не было в 99.14% (1272/1283 случаев) [95% ДИ 0.98;1], было в 0.86% (11/1283 случаев) [95% ДИ 0;0.02].

В выборке после 40 лет прием гормональных препаратов был в 20.83% (265/1283 случаев) [95% ДИ 0.18;0.23], не было 79.17% (1007/1283 случаев) [95% ДИ 0.76;0.81].

В выборке после 40 лет генетической предрасположенности не было в 63.2% (802/1283 случаев) [95% ДИ 0.6;0.65], была в 36.8% (467/1283 случаев) [95% ДИ 0.34;0.39].


При оценке мутация BRCA ее не выявлено было в 1.79% (23/1283 случаев) [95% ДИ 0.01;0.03], мутация BRCA2 была в 0.31% (4/1283 случаев) [95% ДИ 0;0.01], образование не визуализировалось на ММГ в  0.86% (11/1283 случаев) [95% ДИ 0;0.02], ложноположительный результат мутации BRCA был в 0.31% (4/1283 случаев) [95% ДИ 0;0.01].

В выборке после 40 лет сторона поражения при осмотре была правая в 9.9% (127/1283 случаев) [95% ДИ 0.08;0.12], левая - 8.96% (115/1283 случаев) [95% ДИ 0.07;0.11], поражение обеих сторон - 4.75% (61/1283 случаев) [95% ДИ 0.04;0.06], в остальных случаях образование не пальпировалось - 76.38% (980/1283 случаев) [95% ДИ 0.74;0.79].

Кожных симптомы при осмотре нет было в 99.06% (1271/1283 случаев) [95% ДИ 0.98;0.99],  отек был в 0.23% (3/1283 случаев) [95% ДИ 0;0.01], гиперемия была в 0.7% (9/1283 случаев) [95% ДИ 0;0.01].


Втягивание соска при осмотре нет было в 96.02% (1232/1283 случаев) [95% ДИ 0.95;0.97] и было в 3.98% (51/1283 случаев) [95% ДИ 0.03;0.05].

Выделения из соска при осмотре не было в 98.91% (1269/1283 случаев) [95% ДИ 0.98;0.99], светлые выделения были в 0.62% (8/1283 случаев) [95% ДИ 0;0.01], кровянистые были в 0.47% (6/1283 случаев) [95% ДИ 0;0.01].

Тип плотности по ACR при осмотре был «С» в 87.96% (1125/1283 случаев) [95% ДИ 0.86;0.89], тип «D» былл в 12.04% (154/1283 случаев) [95% ДИ 0.1;0.14].

Квадрант локализации верхне-наружный был в 10.52% (135/1283 случаев) [95% ДИ 0.09;0.12], верхне-внутренний в 4.68% (60/1283 случаев) [95% ДИ 0.04;0.06], нижне-наружный в 1.95% (25/1283 случаев) [95% ДИ 0.01;0.03], нижне-внутренний в 1.48% (19/1283 случаев) [95% ДИ 0.01;0.02], граница наружного была в 2.18% (28/1283 случаев) [95% ДИ 0.01;0.03], граница верхнего в 1.64% (21/1283 случаев) [95% ДИ 0.01;0.03], граница нижних было 0.78% (10/1283 случаев) [95% ДИ 0;0.01], вся железа в 0.55% (7/1283 случаев) [95% ДИ 0;0.01], центральный квадрант в 0.55% (7/1283 случаев) [95% ДИ 0;0.01].

### 2.5.3 Описание группы A

### 2.5.4 Описание группы B

### 2.5.5 Описание группы C

### 2.5.6 Описание группы D

### 2.5.7 Оценка однородности групп

## 2.6 Статистический анализ данных
