CREATE DATABASE ABUS
ON
PRIMARY
( NAME = N'ABUS',
    FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ABUS.mdf' ,
    SIZE = 3072KB ,
    MAXSIZE = UNLIMITED ,
    FILEGROWTH = 1024KB ),
FILEGROUP SECONDARY
( NAME = N'ABUS_act',
    FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ABUS_act.ndf' ,
    SIZE = 3072KB ,
    MAXSIZE = UNLIMITED ,
    FILEGROWTH = 1024KB )
LOG ON
( NAME = N'ABUS_log',
    FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ABUS_log.ldf' ,
    SIZE = 1024KB ,
    MAXSIZE = 2048GB ,
    FILEGROWTH = 10%)
COLLATE SQL_Latin1_General_CP1_CI_AS
GO