---
title: "Jun_Accur_3"
author: "Andrey Povaliy"
date: "2023-09-04"
output: html_document
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Диагностической эффективность автоматизированного УЗИ всей молочной железы при раке молочной железы у пациенток до 40 лет.

Рак молочной железы является наиболее распространенным раком среди женщин во всем мире [@shapira2017, @kocarnik2022cancer]. В США у одной из 196 женщин диагностируется рак молочной железы в возрасте до 40 лет. В западной литературе принято использовать термин Подростки и молодые женщины (ПиМЖ[^1]), то есть пациентки в возрасте 15--39 лет [@cathcart-rake2021]. ПиМЖ чаще, чем женщины старшего возраста, имеют агрессивные подтипы и позднюю стадию заболевания, и при постановке диагноза они часто требуют системного определения стадии [@cathcart-rake2021]. Риск смерти от рака молочной железы увеличивается на 5% на каждый год снижения возраста на момент постановки диагноза, что отражает более агрессивные фенотипы, чем рак молочной железы, возникающий в более позднем возрасте [@desreux2018]. Поскольку рак молочной железы среди молодых женщин коррелирует с плохой выживаемостью [@desreux2018], раннее выявление потенциально может улучшить выживаемость, менее инвазивное лечение и более высокое качество жизни, тем самым снижая бремя болезни и затраты на лечение. Однако к вопросам скрининка у ПиМЖ нужно относиться осторожно. Маммография остается золотым стандартом скрининга рака молочной железы. Однако маммография имеет меньшая чувствительность при выявлении рака молочной железы у женщин с плотной грудью, особенно если речь идет о ПиМЖ [@nazari2018]. Согласно исследованиям, скрининг с помощью ручного ултразвукового исследования (УЗИ[^2]) в дополнение к маммографии у женщин с плотной грудью продемонстрировал увеличение показателей выявления рака молочной железы, которые варьировались от 1,8 до 4,6 случаев рака на 1000 обследованных женщин, в зависимости от стратификации населения по риску [@scheel2015; @nazari2018]. Однако исследования программ скрининга в Дании у ПиМЖ [@jorgensen2010] с включением маммографии (ММГ[^3]) показали снижение смертности, объясняется это изменениями факторов риска и улучшением лечения, а не скрининговой ММГ. Однако УЗИ имеет ограничения, а имеено отсутствие стандартизации метода, требуемый высокий уровень навыков и опыта, затраты времени [@rebolj2018]. Поэтому для скрининга рака молочной железы было разработано новое поколение автоматизированного объемного сканирования молочных желез (ABUS[^4]). Новое поколение ABUS предлагает автоматическое сканирование молочной железы с помощью датчика с большим полем обзора, позволяющего получать изображения с высоким разрешением. Между тем, форма зонда специально разработана с учетом нормальной кривизны молочной железы, сводя к минимуму индуцированные артефакты на периферии [@vourtsis2017; @xin2021]. На сегодняшний день ABUS является потенциалом развития в направлениии развития скрининга рака молочножелезы, в частности у ПиМЖ.

[^1]: ПиМЖ - подростки и молодые женщины, термен является точным переводом "adolescent and young adults", термин используется в ангоязычной литертуре, в частности в публикациях системы здравоохранения США

[^2]: УЗИ - ручного ультразвуковое исследование

[^3]: ММГ - маммография

[^4]: ABUS - автоматизированное объемное УЗИ сканирования молочных желез от англ. "3D automated breast ultrasound"

**Цель исследования:** Провести сравнительный анализ диагностической эффективности (чувствительности, специфичности и точности) УЗИ в B-режиме и автоматизированного объемного сканирования молочных желез (ABUS), и комбинации этих методик у женщин в возрастной группе до 39 лет с высокой плотностью тканей молочной железы.

**Материалы и методы**

*Описание выборки*

С февраля 2019 по май 2023 года было исследовано 1506 пациенток с возрастом до 40 лет. Медиана возраста пациенток выборке до 40 лет составил 34 [Q1-Q3: 32;37] лет. Минимальный возраст сотсавил 20 лет, а максимальный сотсавил 39 лет. Медиана роста пациенток выборке до 40 лет составила 167 [Q1-Q3: 164;170] см, а медиана веса составила 59 [Q1-Q3: 55;64] кг.

Всего было поставлено на первичном осмотре врача сформулировано 1517 различных жалоб и вынесено 1533 диагностических заключений у 1506 пациенток. Среди них без патологии было 28.18% (432/1533 случаев) [95% ДИ 0.26;0.31], рак был поставлен в 2.28% (35/1533 случаев) [95% ДИ 0.02;0.03], фиброаденома была поставлена в 19.77% (303/1533 случаев) [95% ДИ 0.18;0.22], фиброзно-кистозная болезнь в 23.68% (363/1533 случаев) [95% ДИ 0.22;0.26], киста в 7.37% (113/1533 случаев) [95% ДИ 0.06;0.09], листовидная опухоль в 0.78% (12/1533 случаев) [95% ДИ 0;0.01], внутрипротоковая папиллома в 0.2% (3/1533 случаев) [95% ДИ 0;0.01], гиперплазия было 0.78% (12/1533 случаев) [95% ДИ 0;0.01]., диффузный фиброаденоматоз было 16.44% (252/1533 случаев)[95% ДИ 0.15;0.18], локализованный фиброаденоматоз было 0.52% (8/1533 случаев)[95% ДИ 0;0.01].

В 78.84% пациентки ни на что не жаловались (1196/1517 случаев) [95% ДИ 0.77;0.81]. Болевой синдром был в 7.38% (112/1517 случаев) [95% ДИ 0.06;0.09], уплотнение в 13.58% (206/1517 случаев) [95% ДИ 0.12;0.15], гиперемия в 0.2% (3/1517 случаев) [95% ДИ 0;0.01].

96.75% исследуемых были в репродуктивном возрасте (1457/1506 случаев) [95% ДИ 0.96;0.98], 2.92% в перменопаузе (44/1506 случаев) [95% ДИ 0.02;0.04], у 0.2% менопауза до 5 лет (3/1506 случаев) [95% ДИ 0;0.01], менопауза более 5 лет были у 0.13% (2/1506 случаев) [95% ДИ 0;0.01]

Операций на молочной железе в анамнезе не было у 98.54% (1484/1506 случаев) [95% ДИ 0.98;0.99], были операции было у 1.46% (22/1506 случаев) [95% ДИ 0.01;0.02].

Прием гормональных препаратов регистрировался у 19.92% исследуемых (300/1506 случаев) [95% ДИ 0.18;0.22], в то время как 80.08% исследуемых не отмечали прием (1206/1506 случаев) [95% ДИ 0.78;0.82].

Генетическая предрасположенность есть была у 33.73% (508/1506 случаев) [95% ДИ 0.31;0.36], у 66.27% ее не было (998/1506 случаев) [95% ДИ 0.64;0.69]. В 97.41% (1467/1506случаев) [95% ДИ 0.96;0.98] определение мутации BRCA не было показано. Выявлена мутация BRCA BRCA1 у 0.2% (3/1506 случаев) [95% ДИ 0;0.01], BRCA2 была у 0.2% (3/1506 случаев) [95% ДИ 0;0.01], в 1.46% анализ не показал мутаций (22/1506 случаев) [95% ДИ 0.01;0.02], в 0.6% (9/1506 случаев) [95% ДИ 0;0.01] была выявлена мутация BRCA образование не визуализировалось на ММГ, ложноположительный результат было в 0.13% (2/1506 случаев) [95% ДИ 0;0.01].

Правая сторона поражения при осмотре была в 13.61% (205/1506 случаев) [95% ДИ 0.12;0.15], левая в 8.76% (132/1506 случаев) [95% ДИ 0.07;0.1], двустороннее поражение было 4.32% (65/1506 случаев) [95% ДИ 0.03;0.06]., в 73.31% при пальпации не было выявлено поражение (1104/1506 случаев) [95% ДИ 0.71;0.76].

Кожные симптомов при осмотре нет было в 99.6% (1500/1506 случаев) [95% ДИ 0.99;1], гиперемия была в 0.4% (6/1506 случаев) [95% ДИ 0;0.01].

Втягивание соска при осмотре не было в 98.14% (1478/1506 случаев) [95% ДИ 0.97;0.99], в то время как в 1.86% (28/1506 случаев) [95% ДИ 0.01;0.03] такой симптом был выявлен.

В 99.14% выделений из соска не было (1493/1506 случаев) [95% ДИ 0.98;1], светлые выделения были в 0.4% (6/1506 случаев) [95% ДИ 0;0.01], кровянистые в 0.46% (7/1506 случаев) [95% ДИ 0;0.01], гноевидные не было зарегистрировано.

Тип плотности «С» по классификации ACR был в 69.59% (1048/1506 случаев) [95% ДИ 0.67;0.72], тип «D» в 30.41% (458/1506 случаев) [95% ДИ 0.28;0.33].

Среди выявленных локализаций на осмотре верхненаружный квадрант был в 32.9% (177/538 случаев) [95% ДИ 0.29;0.37], верхневнутренний в 21% (113/538 случаев) [95% ДИ 0.18;0.25], нижненаружный в 12.64% (68/538 случаев) [95% ДИ 0.1;0.16], нижневнутренний в 3.9% (21/538 случаев) [95% ДИ 0.02;0.06], граница внутреннего в 9.67% (52/538 случаев) [95% ДИ 0.07;0.13], граница наружного в 4.28% (23/538 случаев) [95% ДИ 0.03;0.06], граница верхнего было 11.9% (64/538 случаев) [95% ДИ 0.09;0.15],  граница нижних в 2.79% (15/538 случаев) [95% ДИ 0.02;0.05], вся железа в 0.93% (5/538 случаев) [95% ДИ 0;0.02].

*Описание ABUS*

3D-автоматизированная ультразвуковая система Invenia (ABUS) оцениваемая в данном исследовании, производства GE Healthcare (Саннивейл, Калифорния, США) 2018 года выпуска--- это компьютерная система для оценки плотной молочной железы. Каждая молочная железа была визуализирована в трех проекциях: боковой (LAT), переднезадней (AP).и медиальный (MED) с автоматическим датчиком с линейной матрицей от 6 до 14 МГц, прикрепленным к жесткой компрессионной пластине.(площадь 15,4×17,0×5,0 см).Индивидуальная мембрана для датчика была использована для каждой пациентки. Во время исследования система получала до 300 2D-срезов и реконструировала их в коронарной плоскости. Стандартизированный процесс осмотра включает использование запатентованной коронарной плоскости для быстрой навигации по молочной железе, а также использование «режима обзора», позволяющего врачу быстро интерпретировать изображения. Время сбора данных для каждой проекции составляло 60 с, примерно по 3--4 мин на каждую молочную железу.

Обследование проводили в положении лежа. Полотенце было помещено под плечом, что помогло расправить ткань молочной железы равномерно, соском к потолку. На молочные железы равномерно наносили гипоаллергенный ультразвуковой гель с дополнительным количество на область соска. Возможно применение трех уровней компрессии датчика для исследования молочных желез для получения наилучшей визуализации с учетом комфорта пациента.

Сканирование ABUS было непрерывным и автоматизированным. В течение исследования женщин попросили не двигаться, не разговаривать и дышать ровно. Выполнял исследование сертифицированный персонал со средним медицинским образованием.

После завершения сбора данных ультразвуковой системой весь массив передавался на специальную рабочую станцию для интерпретации. Оценку изображений ABUS выполнял один врач ультразвуковой диагностики, со стажем работы более 7 лет. Общее время, необходимое для подготовки пациента и получения ABUS, фиксировалось,

*Описание УЗИ-исседования*

УЗИ мсследование выполняли два врача ультразвуковой диагностики со стажем работы более 7 лет. Исследование проводилось в положении лежа, с руками за головой, с последовательным сканированием каждого квадранта обеих молочных железе в сагитальной и аксиальной плоскостях, с исследованием ретроареолярной области и аксиллярных областей с двух сторон.

Устройства, используемые для проведения HHUS включали GE LOGIQS 8 (GE Medical Systems, Милуоки, Висконсин, США), Toshiba Aplio 300(Canon Япония)- ультразвуковые системы экспертного класса.

*Статистический анализ*

**Результаты**

**Дисскусия**

**Выводы**
