@startuml
start
:Консультация гинеколога/онколога;
group <b>1. Преддиагностический этап </b>
:Сбор жалоб;
:Сбор анамнеза;
:Визуальный осмотр и пальпация;
end group
group <b>2. Согласие на исследование </b>
:Пациентка подписывает согласие на исследование;
end group

group <b>3.  Клиническое исследование </b>
if (Распределение в группу) then (A)
:Проведение 2D УЗИ;

else(B)

:Проведение 2D УЗИ;
:Проведение 3D УЗИ;

endif

if (BiRads 1 и 2 \nпо результату 2D УЗИ) then (да)
#palegreen:Дальнейшее наблюдение;
stop
else(нет)
if  (BiRads 3 \nпо результату 2D УЗИ) then (да)
#PeachPuff:Наблюдение 3-6 мес \nИли МРТ с КУ;
stop
else(нет)
:BiRads 4 и BiRads 5; 
#salmon:Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия;
stop
@endumll