@startuml
(Всего \n N = 1511) --> ( Birads 1 \n N = 359)
(Всего \n N = 1511) --> ( Birads 2 \n N = 856)
(Всего \n N = 1511) --> (Birads 3 \n N = 229)
(Всего \n N = 1511) --> ( Birads 4a \n N = 34)
(Всего \n N = 1511) --> ( Birads 4b \n N = 12)
(Всего \n N = 1511) --> ( Birads 5 \n N = 21)
(Birads 3 \n N = 229) --> (Birads 3 \n N = 33)
(Birads 3 \n N = 33) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 100)
( Birads 4a \n N = 34) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 100)
( Birads 4b \n N = 12) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 100)
( Birads 5 \n N = 21) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 100)
@endumll