@startuml
start
:Консультация гинеколога или онколога;
group <b>1. Преддиагностический этап</b>
:Сбор жалоб;
:Сбор анамнеза;
:Визуальный осмотр и пальпация;
#Orchid:Проведение дигностической маммографии;
end group
group <b>2. Согласие на исследование</b>
:Пациентка подписывает согласие на исследование;
end group

group <b>3.  Клиническое исследование </b>
if (Распределение в группу ) then (А)
#Orchid:Проведение 2D УЗИ;




else(Б)

#Orchid:Проведение 2D УЗИ;

#Orchid:Проведение 3D УЗИ;

endif

if (BI-RADS 1 и 2 \nпо результату УЗИ) then (да)
#palegreen:Дальнейшее наблюдение;
stop
else(нет)
if  (BI-RADS 3 \nпо результату УЗИ) then (да)
#PeachPuff:Наблюдение 3-6 мес \n или МРТ с КУ;
#salmon:Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия;
stop
else(нет)
:BI-RADS 4 и 5;
#salmon:Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия;
stop
@endumll
