@startuml
start
:Консультация гинеколога или онколога/\n Consultation with a gynecologist or oncologist;
group <b>1. Преддиагностический этап</b>/\n <b>1. Pre-diagnostic stage </b>
:Сбор жалоб/\n Collection of complaints;
:Сбор анамнеза/\n Collection of anamnesis;
:Визуальный осмотр и пальпация/\n Visual inspection and palpation;
#Orchid:Проведение дигностической маммографии/\n Performing a diagnostic mammography;
end group
group <b>2. Согласие на исследование</b>/\n  <b>2. Consent to Study</b>
:Пациентка подписывает согласие на исследование/\n The patient signs the consent for the study;
end group

group <b>3.  Клиническое исследование </b> /\n <b>3.  Clinical Trial </b>
if (Распределение в группу /\n Group assignment ) then (А/А)
#Orchid:Проведение 2D УЗИ/\n 2D  Ultrasound;




else(Б/B)

#Orchid:Проведение 2D УЗИ /\n 2D  Ultrasound;

#Orchid:Проведение 3D УЗИ /\n 3D ultrasound;

endif

if (BI-RADS 1 и 2 \nпо результату УЗИ/\ n BI-RADS 1 and 2 \naccording to the ultrasound result) then (да/yes)
#palegreen:Дальнейшее наблюдение/\n Follow-up;
stop
else(нет/no)
if  (BI-RADS 3 \nпо результату УЗИ /\ n BI-RADS 3 \nbased on ultrasound) then (да/yes)
#PeachPuff:Наблюдение 3-6 мес \n или МРТ с КУ /\ n Follow-up for 3-6 months \n or MRI with CE;
#salmon:Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy;
stop
else(нет/no)
:BI-RADS 4 и 5 /\n BI-RADS 4 and 5;
#salmon:Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy;
stop
@endumll
