@startuml
(Всего/Total \n N = 1283) --> ( BI-RADS 1 \n N = 29)
(Всего/Total \n N = 1283) --> ( BI-RADS 2 \n N = 942)
(Всего/Total \n N = 1283) --> (BI-RADS 3 \n N = 122)
(Всего/Total \n N = 1283) --> ( BI-RADS 4a \n N = 52)
(Всего/Total \n N = 1283) --> ( BI-RADS 4b \n N = 37)
(Всего/Total \n N = 1283) --> ( BI-RADS 4c \n N = 28)
(Всего/Total \n N = 1283) --> ( BI-RADS 5 \n N = 73)
(BI-RADS 3 \n N = 122) --> (МРТ/MRSI)
(МРТ/MRSI)--> (BI-RADS 2 \n N = 78)
(МРТ/MRSI)--> (BI-RADS 4а \n N = 44)
(BI-RADS 4а \n N = 44) --> (Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy\n N = 234)
( BI-RADS 4a \n N = 52) --> (Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy\n N = 234)
( BI-RADS 4b \n N = 37) --> (Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy\n N = 234)
( BI-RADS 4c \n N = 28) --> (Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy\n N = 234)
( BI-RADS 5 \n N = 73) --> (Core биопсия/\nСтереотаксическая биопсия/\nПункционная биопсия/\n Core biopsy/\nStereotactic biopsy/\nNeedle biopsy\n N = 234)
@endumll