@startuml
(Всего \n N = 1283) --> ( Birads 1 \n N = 29)
(Всего \n N = 1283) --> ( Birads 2 \n N = 942)
(Всего \n N = 1283) --> (Birads 3 \n N = 122)
(Всего \n N = 1283) --> ( Birads 4a \n N = 52)
(Всего \n N = 1283) --> ( Birads 4b \n N = 37)
(Всего \n N = 1283) --> ( Birads 4c \n N = 28)
(Всего \n N = 1283) --> ( Birads 5 \n N = 73)
(Birads 3 \n N = 122) --> (Birads 3 \n N = 44)
(Birads 3 \n N = 44) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 234)
( Birads 4a \n N = 52) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 234)
( Birads 4b \n N = 37) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 234)
( Birads 4c \n N = 28) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 234)
( Birads 5 \n N = 73) --> (Core биопсия/\nСтереотаксическаябиопсия/\nПункционная биопсия \n N = 234)
@endumll