---
title: "Calc_abus_accur"
author: "AndreyPovaliy"
date: "2023-11-28"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Определение чувствительности, спецефичности и точности автоматизированного трехмерного 3d сканера для обнаружения кальцинатов при скрининге рака молочной железы

## Введение

## Цель исследования



## Материалы и методы

С февраля 2019 по май 2023 года проводилось ретро-проспективное
наблюдательное исследование, в котором рассматривались диагностические
аспекты раннней диагностики рака молочной железы с реди женщин в
возрасте 40 лет и старше. Среди исследуемых диагностических методи
рассматривались УЗИ, ABUS и маммография. Протокол настоящего
исследования был одобрен на заседании локального этического комитета
СЗГМУ им.Мечникова №00 от ХХ.ХХ.ХХХХ года.

*Последовательность проведения диагностики*



*Описание выборки и групп*



*Описание ABUS*



*Описание маммографии*

*Описание УЗИ-исседования*




## Результаты исследования 



## Дисскусия


## Выводы


исследования.

## Список литературы