@startuml
start
:Консультация гинеколога/онколога;

#Orchid:Поведение дигностической маммографии;

group <b>1. Согласие на исследование </b>
:Пациентка подписывает согласие на исследование;
end group

group <b>2.  Клиническое исследование </b>

#Orchid:Проведение УЗИ;

#Orchid:Проведение ABUS;


:Проведение сравнения по эффекиттивности обнаружения кальцинатов;
stop
@endumll