@startuml

:Консультация гинеколога/онколога;

#GreenYellow:Поведение дигностической маммографии;

group <b>1. Согласие на исследование </b>
:Пациентка подписывает согласие на исследование;
end group

group <b>2.  Клиническое исследование </b>

#SkyBlue:Проведение 2d УЗИ в B-режиме MicroPure;

#SkyBlue:Проведение 3d УЗИ;


:Проведение сравнения по эффекитивности \nобнаружения микрокальцинатов;

@endumll