---
title: "AutoRef"
author: "AndreyPovaliy"
date: "2025-01-25"
output: html_document
bibliography: references.bib
csl: gost-r-7-0-5-2008.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Title list

На правах рукописи

Гаранина Анна Эдуардовна

РОЛЬ АВТОМАТИЗИРОВАННОГО ОБЪЕМНОГО УЛЬТРАЗВУКОВОГОСКАНИРОВАНИЯ В КОМПЛЕКСНОЙ РАННЕЙ ДИАГНОСТИКЕ ОБРАЗОВАНИЙМОЛОЧНЫХ ЖЕЛЕЗ

3.1.25 – лучевая диагностика

Автореферат диссертации на соискание ученой степени кандидата медицинских наук

Санкт-Петербург 2025

# ОБЩАЯ ХАРАКТЕРИСТИКА РАБОТЫ

**Актуальность темы исследования.** Рак молочной железы (РМЖ) относится к серьезной глобальной проблеме здравоохранения: это наиболее часто диагностируемый вид рака в мире. Количество случаев РМЖ, зарегистрированных в 2020 году, составило 2,26 миллиона [@wilkinson2022], причем более половины из них зарегистрированы в менее развитых регионах мира [@sung2021].

Наблюдаемое преимущество в выживаемости пациентов с диагностированным РМЖ в более развитых странах в значительной степени может быть связано с сочетанием стратегий раннего выявления, доступа к ранней диагностике и эффективным методам лечения.

Напротив, отсроченное проявление чаще встречается в менее развитых регионах мира, где более половины случаев РМЖ относятся местно-распространенному или метастатическому. РМЖ представляет наиболее распространенный вид рака, диагностируемый ежегодно среди женщин (более 1 из 10 новых ежегодных случаев РМЖ). В соответствии с данными ВОЗ и The Global Cancer Observatory (GCO), РМЖ --- самое распространенное онкологическое заболевание у женщин с частотой выявления 46,4 на 100 тыс. женщин в мире и 53,6 на 100 тыс. в Российской Федерации (РФ).

Анализ данных по частоте выявления злокачественных новообразований (ЗНО) у женщин свидетельствует о том, что после РМЖ следуют злокачественные новообразования кожи (15,2%, с меланомой -- 17,2%), тела матки (7,8%), ободочной кишки (7,3%), шейки матки (5,0%), лимфатической и кроветворной ткани (4,7%), прямой кишки, ректосигмоидного соединения, ануса (4,4%), желудка (4,4%), яичника (4,1%), трахеи, бронхов, легкого (3,8%) [@mahvi2018; @каприн2017злокачественные; @каприн2020состояние; @кушунина2019выявление]. РМЖ также является основной причиной смерти от ЗНО среди женщин; смертность от РМЖ в мире составляет 13,0 на 100 тыс. женщин, в РФ --- 15,1 на 100 тыс.

Большинством руководств маммографический скрининг был рекомендован женщинам в возрасте 40--74 лет [@siu2016; @hamashima2016; @qaseem2019; @ren2022; @urban2017], женщинам в возрасте 50--69 лет проведение скрининга было обязательным [@schünemann2019; @wöckel2018; @ren2022; @migowski2018].

Точное измерение плотности МЖ поможет в более точной стратификации риска развития РМЖ (прогностической и профилактической), позволит определиться с необходимым объемом дополнительных диагностических методик исследования плотности МЖ как независимого фактора риска развития РМЖ.

Американский колледж радиологии (ACR) в 3-ем издании BI-RADS описывает плотность груди с точки зрения четырех категорий общей плотности. Первоначально эти категории были простыми описательными терминами («жировая», «рассеянная плотность», «гетерогенно плотная» и «чрезвычайно плотная») [@d2018breast].

Литературные данные подтверждают факт того, что женщины с плотной МЖ типа d имеют четырех-шестикратное увеличение риска по сравнению с женщинами с плотностью МЖ типа a [@boyd2013; @lee2012]. Именно плотность МЖ в общей популяции чаще по сравнению с другими факторами (возраст, генетические мутации (BRCA 1/BRCA2)) является самым сильным предиктором РМЖ.

В некоторых исследованиях было высказано предположение, что только показатель плотности МЖ вносит значительный вклад в риск развития РМЖ на популяционном уровне, составляя 16% всех диагностированных РМЖ [@boyd2011; @bae2014; @boyd2007; @fasching2006].

По мнению большинства исследователей интервальный рак (рак, выявленный в промежутке между запланированными скрининговыми маммограммами) в 13-31 раз более вероятен в груди с плотностью типа d, чем в МЖ с плотностью типа a (исследования Posso M., 2019) [@posso2019; @boyd2007; @ciatto2004; @strand2019].

Плотность груди также является биомаркером для прогнозирования ответа на неоадъювантную химиотерапию. Skarping, I.et al. (2019 г.) в своем исследовании показали, что женщины в пременопаузе с высокой маммографической плотностью плохо реагируют на неоадъювантную химиотерапию [@skarping2019].

Маммографическая плотность МЖ длительное время была предметом дискуссий между учеными и практическими докторами. В частности, активно обсуждался вопрос необходимости информирования женщин о наличии у них высокой плотности МЖ [@almousa2014; @machida2015; @tossas-milligan2019].Большинство авторов сходятся во мнении, что женщины должны быть проинформированы в связи с тем, что плотная ткань МЖ может 1) скрывать опухоли на маммограмме, 2) повышать риск развития РМЖ и 3) требовать проведения дополнительных методов исследований, таких как УЗИ и магнитно-резонансной томографии (МРТ) [@tossas-milligan2019].

Таким образом в настоящее время требуется изученеи возможностей новых методов скрининга МЖ.

**Степень разработанности темы исследования.** Развитие автоматизированного ультразвукового томосинтеза (АУС/ABUS/ABVS) является одним из наиболее перспективных направлений, который позволяет получить в среднем за 3 сканирования (коронарная, сагиттальная и аксиальная) плоскости изображение всей МЖ.

Кроме того, разработано специальное программное обеспечение для 3D ABUS с целью автоматизированного обнаружения патологических образований (CAD) (QVCAD™, QView Medical), которое получило одобрение FDA [@vourtsis2019]. Восемнадцатью рентгенологами, участвовавшими в исследовании Y. Jiang, M.F. et al. (2018), без системы QVCAD среднее время интерпретации результатов МЖ составляло 3 минуты 33 секунды для каждого случая, но уменьшалось до 2 минут 24 секунд при внедрении QVCAD, при этом разница соответствует 1 минуте 9 секундам, сэкономленным на каждом случае [@jiang2018].

Анализ различных исследований показал более высокие или равные результаты обнаружения поражений МЖ с помощью 3D ABUS по сравнению с УЗИ. Показатели обнаружения с помощью 3D ABUS варьируют от 84,8% до 100%, тогда как соответствующие показатели для ультразвукового метода- от 60,6% до 100% [@wang2012; @xiao2015; @wang2012a; @lin2012; @kim2013; @vourtsis2019].

В литературе также встречается достаточное количество работ, посвященных дифференциации злокачественных и доброкачественных образований МЖ с помощью 3D ABUS [@chou2007automated; @golatta2013; @golatta2014; @kotsianos-hermle2009].

3D ABUS, благодаря хорошей визуализации МЖ также является новым методом оперативного планирования [@grady2010]; размер поражения, определенный с помощью 3D ABUS, хорошо коррелирует с результатами МРТ [@schmachtenberg2017] и гистопатологическими изменениями [@chang2015].

Коронарная плоскость имеет особое значение для хирургического планирования из-за лучшей визуализации сегментарного доступа и схожей ориентации при позиционировании пациента во время операции [@amy2018lobar]. 3D ABUS также позволяет визуализировать сателлитные очаги размером менее 1 см, что очень ценно в оценке многоочагового рака.

3D ABUS может применяться при оценке результатов МРТ в качестве уточняющей методики [@halshtok2015use; @girometti2017]: так, например, 3D ABUS превзошла УЗИ в качестве вторичного исследования после проведения МРТ МЖ, выявив дополнительные очаги [@kim2016].

В работах отечественных исследователей (В.Е. Гажонова, М.П. Ефремова, Е.М. Бачурина, Е.М. Хлюстина, С.Б. Поткин) изучались возможности данной методики в определении типа строения МЖ среди женщин разных возрастных групп, имеющих различную патологию. Полученные ими данные свидетельствовали и значительном увеличении специфичности данного метода (до 96%) у пациенток с типами плотности МЖ с и d, что может иметь важное значение при скрининге женщин данной категории [@гажонова2015возможности].

Добавленную ценность ABUS к ММГ при высокой плотности МЖ исследовали также Wilczek, Leifland и другие. Ученые доказали повышение выявляемости РМЖ на 57% [@vourtsis2018].

ABUS--- это технологический прогресс в области визуализации и скрининга МЖ с преимуществами стандартизации сканирований, лучшего обнаружения небольших поражений, особенно у женщин с повышенной плотностью МЖ, и сокращения времени сканирования. Продолжаются интенсивные исследования новых разработок и исследований дополнительных приложений технологии 3D ABUS. Оценка плотности МЖ с помощью 3D ABUS также является еще одним перспективным направлением.

**Цель работы:** повысить эффективность выявления непальпируемых опухолей молочных желез.

**Задачи исследования**

1.Провести сравнительный анализ диагностической эффективности (чувствительности, специфичности и точности,) ультразвукового исследования в B- режиме и автоматизированного объемного сканирования молочных желез (3D УЗИ), и комбинации этих методик у женщин в возрастной группе 30-39 лет с высокой плотностью тканей молочной железы.

2.Провести сравнительный анализ диагностической эффективности (чувствительности, специфичности и точности,) цифровой маммографии, ультразвукового исследования в B-режиме и автоматизированного объемного сканирования молочных желез (3D УЗИ), и комбинации этих методик у женщин в возрастной группе 40-69 лет с высокой плотностью тканей молочной железы.

3.Определить прогностическую ценность методики автоматизированного объемного сканирования молочных желез (3D УЗИ) в диагностике образований молочной железы у женщин разных возрастных групп.

4 Изучить возможность визуализации кальцинатов на 3D сонотомограммах и в 2D режиме ультразвукового исследования с использованием дополнительной функции Micro Pure.

5.Оптимизировать алгоритмы обследования женщин с образованиями молочных желез с использованием возможностей нового метода автоматизированного объемного ультразвукового сканирования.

**Научная новизна**

1.  Впервые в нашей стране проведен сравнительный анализ эффективности методик традиционной рентгеновской маммографии, ультразвукового исследования в 2D режиме и автоматизированного объемного ультразвукового сканирования (3D УЗИ) у женщин в разных возрастных группах.

2.  Была определена прогностическая ценность автоматизированного объемного ультразвукового сканирования в комплексной диагностике не пальпируемых образований молочных желез.

3.  Было определено место нового метода в мультимодальном лучевом алгоритме обследования женщин с плотной молочной железой в разных возрастных группах.

**Теоретическая и практическая значимость работы**

1.  Прогностическая ценность автоматизированного объемного ультразвукового сканирования в комплексной диагностике не пальпируемых образований молочных желез в группе паценток до 40 лет может позволить разрабатывать новые подходы к скринингу.

2.  Прогностическая ценность автоматизированного объемного ультразвукового сканирования в комплексной диагностике не пальпируемых образований молочных желез в группе паценток 40 лет также изучена и в этой группе могут быть разработаны подходы к скринингу с учетом полученных знаний.

3.  Данные, полученные при оределений алгоритма позволят уточнить по каким принципам проводить скрининг с использованием автоматизированного объемного ультразвукового сканирования в комплексной диагностике не пальпируемых образований молочных желез.

**Методология и методы исследования**

Исследование можно характеризовать как клиническое исследование диагностических аспектов ранней диагностики рака молочной железы. Объектом исследования являются новообразования молочной железы, регистрируемые при диагностике с использованием ручного ультразвукового исследования (УЗИ), маммографии (ММГ) и автоматизированного объемного УЗИ сканирования молочных желез (ABUS). Предметом исследования является изучение диагностической эффективности автоматизированного объемного УЗИ сканирования молочных желез, а также анализ наиболее важных факторов как преддиагностическом этапе, так и при выполнении конкретного диагностического метода, в частности при выполнении автоматизированного объемного УЗИ сканирования молочных желез. Дизайн исследования можно охарактеризовать ретро-проспективное наблюдательное исследование. Протокол настоящего исследования был одобрен на заседании локального этического комитета СЗГМУ им. Мечникова №9 от 12.10.2022 года.

Всего в исследование вошло 2794 пациенток. Критерии включения были пациенты женского пола в возрасте от 18 до 80 лет; женщина, посетившая врача для обследования рака молочной железы, с отсутствием видимых признаков рака молочной железы. Критериями исключения были: женщины, которые были беременны, кормили грудью или планировали забеременеть; оперативное лечение в анамнезе (лампэктомия, мастэктомия, увеличение груди), Эксцизионная или чрескожная биопсия за последние 12 месяцев, пациентки, получавшие лечение по поводу рака молочных желез за последние 12 месяцев. В это исследование была включена одна медицинская клиника- «СМТ», состоящая из двух зданий -амбулаторно-поликлического комплекса и хирургического корпуса со стационаром. Все женщины из амбулаторного отделения были приглашены для участия в нашем исследовании, участники подписали форму информированного согласия. Все обследования были проведены медицинским персоналом с соответствующей квалификацией. Всем провели клинический осмотр, пальпацию, собрали информацию о социально-демографических данных и потенциальных факторах риска РМЖ.

Все пациентки были разделены на 2 независимые друг от друга выборки по принципу возраста: выборка пациенток с возрастом до 40 лет и выборка пациенток с возрастом от 40 лет включительно. Принцип разделения по возрасту был связан с различными принципами использования диагностических методов в скрининге рака молочной железы. У пациенток моложе 40 лет ММГ менее эффективна, так как низкая чувствительность метода и основным методом диагностики используется УЗИ метод [@mandelson2000].

У пациенток моложе от 40 лет метод ММГ является обязательным в скрининге РМЖ [@narayan2020]. Более подробно об используемых методах можно прочитать в разделе “2.3 Описание диагностических методов”. В выборку до 40 лет вошло 1511 пациенток. Эта выборка пациенток была разделена на две группы A и B. В группу A вошло 724 пациенток и в это группе скрининг проводился с использованием мануальной УЗИ диагностики и автоматизированного объемного УЗИ сканирования молочных желез (исследуемая группа). В группу B вошло 787 пациенток и в этой группе скрининг проводился только с использованием ручного УЗИ диагностики (контрольная группа). В выборку 40 лет и старше вошло 1283 пациенток. Эта выборка пациенток была разделена на две группы С и D. В группу С вошло 655 пациенток и в это группе скрининг проводился с использованием ручного УЗИ, маммографии и автоматизированного объемного УЗИ сканирования молочных желез (исследуемая группа). В группу D вошло 628 пациенток и в этой группе скрининг проводился только с использованием ручного УЗИ и маммографии (контрольная группа). Подробное описание выборок и групп представлено в разделе “2.5 Описание исследуемых групп”. Включение указанного количества пациенток в группы было основано на расчете мощности, более подробно можно прочитать в разделе “2.6 Статистический анализ данных”.

Диагностический этап, где проводилась непосредственно диагностическое исследование с использованием методом ручного УЗИ исследования, маммографии и автоматизированного объемного УЗИ сканирования молочных желез в зависимости от группы распределения.

Производился сбор данных для последующего выявления наиболее значимых факторов, а также выявления эффективности изучаемых методов и прогностической ценности метода. 2D УЗИ выполняли два врача ультразвуковой диагностики со стажем работы более 7 лет. Исследование проводилось в положении лежа, с руками за головой, с последовательным сканированием каждого квадранта обеих молочных железе в сагитальной и аксиальной плоскостях, с исследованием ретроареолярной области и аксиллярных областей с двух сторон. Устройства, используемые для проведения 2D УЗИ включали GE LOGIQS 8 (GE Medical Systems, Милуоки, Висконсин, США), Toshiba Aplio 300 (Canon Япония)- ультразвуковые системы экспертного класса. D-автоматизированная ультразвуковая система Invenia (ABUS) оцениваемая в данном исследовании, производства GE Healthcare (Саннивейл, Калифорния, США) 2018 года выпуска— это компьютерная система для оценки плотной молочной железы.

Каждая молочная железа была визуализирована в трех проекциях: боковой (LAT), переднезадней (AP).и медиальный (MED) с автоматическим датчиком с линейной матрицей от 6 до 14 МГц, прикрепленным к жесткой компрессионной пластине.(площадь 15,4×17,0×5,0 см).Индивидуальная мембрана для датчика была использована для каждой пациентки. Во время исследования система получала до 300 2D-срезов и реконструировала их в коронарной плоскости. Стандартизированный процесс осмотра включает использование запатентованной коронарной плоскости для быстрой навигации по молочной железе, а также использование «режима обзора», позволяющего врачу быстро интерпретировать изображения. Время сбора данных для каждой проекции составляло 60 с, примерно по 3–4 мин на каждую молочную железу. Обследование проводили в положении лежа. Полотенце было помещено под плечом, что помогло расправить ткань молочной железы равномерно, соском к потолку. На молочные железы равномерно наносили гипоаллергенный ультразвуковой гель с дополнительным количество на область соска. Возможно применение трех уровней компрессии датчика для исследования молочных желез для получения наилучшей визуализации с учетом комфорта пациента.

Сканирование ABUS было непрерывным и автоматизированным. В течение исследования женщин попросили не двигаться, не разговаривать и дышать ровно. Выполнял исследование сертифицированный персонал со средним медицинским образованием. После завершения сбора данных ультразвуковой системой весь массив передавался на специальную рабочую станцию для интерпретации. Оценку изображений ABUS выполнял один врач ультразвуковой диагностики, со стажем работы более 7 лет. Общее время, необходимое для подготовки пациента и получения ABUS, фиксировалось, в каждом случае и варьировалось примерно между 10 и 15 мин.

Пациентки старше 40 лет прошли двухпроекционную цифровую маммографию (в медиалатеральной косой и краниокаудальной проекции) обеих молочных желез. Маммографию также выполняли женщинам моложе 40 лет в случае положительного семейного или личного анамнеза - рак молочной железы. Используемое оборудование- Planmed Clarity 3D с функцией томосинтеза (Финляндия). Оценку изображений проводил один рентгенолог со стажем работы более 10 лет.

Диагностика МРТ проводилась на высокопольном магнитно-резонансном томографе General Electric Medical Systems Signa HDxt 1,5 Т (США). Показаниями к проведению МРТ была поставленная после проведения ручного УЗИ категория 3 по классификации по BI-RADS.

Результаты выявленных изменений были классифицированы по BI-RADS отсортированы по шести категориям [@spak2017]: 0 = неполные данные, 1 = нормальные, 2 = доброкачественные, 3 =вероятно доброкачественные, 4 = подозрительные, 5 = с высокой степенью вероятности злокачественные, для HHUS, ABUS и MG. Для категории Birads 3 обязательно проводилась магнитно-резонансная томография (МРТ) для выявления истинно отрицательных и ложноотрицательных результатов. Женщинам, отнесенным к категории 4 или 5, проводилась трепан биопсия под уз-наведением или стереотаксическим наведением с последующей морфологической и при необходимости иммуногистохимической верификацией.

**Положения, выносимые на защиту:**

Диагностическая эффективность автоматизированного УЗИ молочных желез у пациенток до 40 лет сопоставима по показателю специфичности и лучше по показателю точности, чувствительности, лучше прогностическая модель метода по сравнению с ультразвуковым исследованием в 2D режиме.

Диагностическая эффективность автоматизированного 3D-УЗИ молочных желез у пациенток 40 лет и старше сопоставима по показателю чувствительности и лучше по показателю точности, специфичности по сравнению с ультразвуковым исследованием в 2D режиме.

Предлагаемый оптимизированный алгоритм определяет место 3D УЗИ в структуре скрининга рака молочной железы и потенциально может снизить нагрузку на врачей ультразвуковой диагностики и сократить время на проведение исследования.

**Степень достоверности и апробация результатов.**

Достоверность полученных результатов определяется достаточным количеством набранного материала для решения поставленной цели и задач исследования. Выбраны адекватные статистические методы обработки данных. Объем проведенной работы достаточен для решения поставленных задач, цели исследования и обоснования выводов, и клинических рекомендаций. Основные положения настоящего диссертационного исследования были доложены на невском радиологическом форуме ( Сборник тезисов XV международного конгресса, Санкт-Петербург, 12–13 апреля 2024 года), на всероссийском конгрессе ординаторов медицинских вузов «Научно-практическая подготовка ординаторов(СПб, 2024), на конференции «Fundamental аnd applied sciences today XXXIII”-ХXXIII международной научно-практической конференции «Фундаментальные и прикладные науки сегодня» (Bengaluru, Karnataka, India, 2024).

**Личное участие автора в получение результатов.**

Автор настоящего исследования определил цель и задачи, разработал методологические подходы и дизайн исследования совместно с научным руководителем. Статистической обработка полученных результатов была проведена самостоятельно.

**Объем и структура диссертации**

Диссертация изложена на 195 страницах машинописного текста, иллюстрирована 32 рисунками, содержит 28 таблиц; состоит из введения, обзора литературы, характеристики исследуемых пациентов и описания методов исследования, а также 6 глав собственных исследований, заключения, выводов, практических рекомендаций и списка литературы, содержащего 179 источников, из них 25 отечественных и 154 иностранных.

# ОСНОВНОЕ СОДЕРЖАНИЕ РАБОТЫ

## Материалы и методы

Исследование можно характеризовать как клиническое исследование диагностических аспектов ранней диагностики рака молочной железы. Объектом исследования являются новообразования молочной железы, регистрируемые при диагностике с использованием ручного ультразвукового исследования (УЗИ), маммографии (ММГ) и автоматизированного объемного УЗИ сканирования молочных желез (ABUS). Предметом исследования является изучение диагностической эффективности автоматизированного объемного УЗИ сканирования молочных желез, а также анализ наиболее важных факторов как преддиагностическом этапе, так и при выполнении конкретного диагностического метода, в частности при выполнении автоматизированного объемного УЗИ сканирования молочных желез. Дизайн исследования можно охарактеризовать ретро-проспективное наблюдательное исследование. Протокол настоящего исследования был одобрен на заседании локального этического комитета СЗГМУ им. Мечникова №9 от 12.10.2022 года.

Всего в исследование вошло 2794 пациенток. Критерии включения были пациенты женского пола в возрасте от 18 до 80 лет; женщина, посетившая врача для обследования рака молочной железы, с отсутствием видимых признаков рака молочной железы. Критериями исключения были: женщины, которые были беременны, кормили грудью или планировали забеременеть; оперативное лечение в анамнезе (лампэктомия, мастэктомия, увеличение груди), Эксцизионная или чрескожная биопсия за последние 12 месяцев, пациентки, получавшие лечение по поводу рака молочных желез за последние 12 месяцев. В это исследование была включена одна медицинская клиника- «СМТ», состоящая из двух зданий -амбулаторно-поликлического комплекса и хирургического корпуса со стационаром. Все женщины из амбулаторного отделения были приглашены для участия в нашем исследовании, участники подписали форму информированного согласия. Все обследования были проведены медицинским персоналом с соответствующей квалификацией. Всем провели клинический осмотр, пальпацию, собрали информацию о социально-демографических данных и потенциальных факторах риска РМЖ.

Все пациентки были разделены на 2 независимые друг от друга выборки по принципу возраста: выборка пациенток с возрастом до 40 лет и выборка пациенток с возрастом от 40 лет включительно. Принцип разделения по возрасту был связан с различными принципами использования диагностических методов в скрининге рака молочной железы. У пациенток моложе 40 лет ММГ менее эффективна, так как низкая чувствительность метода и основным методом диагностики используется УЗИ метод [@mandelson2000]. У пациенток моложе от 40 лет метод ММГ является обязательным в скрининге РМЖ [@narayan2020]. Более подробно об используемых методах можно прочитать в разделе “2.3 Описание диагностических методов”.

В выборку до 40 лет вошло 1511 пациенток. Эта выборка пациенток была разделена на две группы A и B. В группу A вошло 724 пациенток и в это группе скрининг проводился с использованием мануальной УЗИ диагностики и автоматизированного объемного УЗИ сканирования молочных желез (исследуемая группа). В группу B вошло 787 пациенток и в этой группе скрининг проводился только с использованием ручного УЗИ диагностики (контрольная группа). В выборку 40 лет и старше вошло 1283 пациенток. Эта выборка пациенток была разделена на две группы С и D. В группу С вошло 655 пациенток и в это группе скрининг проводился с использованием ручного УЗИ, маммографии и автоматизированного объемного УЗИ сканирования молочных желез (исследуемая группа). В группу D вошло 628 пациенток и в этой группе скрининг проводился только с использованием ручного УЗИ и маммографии (контрольная группа). Подробное описание выборок и групп представлено в разделе “2.5 Описание исследуемых групп”. Включение указанного количества пациенток в группы было основано на расчете мощности, более подробно можно прочитать в разделе “2.6 Статистический анализ данных”.

Диагностический этап, где проводилась непосредственно диагностическое исследование с использованием методом ручного УЗИ исследования, маммографии и автоматизированного объемного УЗИ сканирования молочных желез в зависимости от группы распределения.

Производился сбор данных для последующего выявления наиболее значимых факторов, а также выявления эффективности изучаемых методов и прогностической ценности метода.

## Основные результаты исследования

# ВЫВОДЫ

# ПРАКТИЧЕСКИЕ РЕКОМЕНДАЦИИ

# ПЕРСПЕКТИВЫ ДАЛЬНЕЙШЕЙ РАЗРАБОТКИ ТЕМЫ

# Список печатных работ, опубликованных по теме диссертации

# Список сокращений, используемых в автореферате

Гаранина, А.Э. Роль автоматизированного объемного ультразвукового сканирования в комплексной ранней диагностике образований молочных желез: автореф. дис. … канд. мед наук: 3.1.25 / Гаранина Анна Эдурдовна. – СПб., 2025. – 24 с.
