---
title: "Snr_Accur_4"
author: "AndreyPovaliy"
date: "2023-11-24"
output: word_document
bibliography: references2.bib
csl: american-medical-association-brackets.csl
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

УДК 616-006.04

# Эффективность автоматизированного 3D-УЗИ молочной железы у женщин 40 лет и старше с неоднородной и плотной грудью

Гаранина А.Э., Холин А.В.

Северо-Западный государственный Медицинский университет им. И. И.
Мечникова, Россия, Санкт-Петербург, 191015, Российская Федерация, г.
Санкт-Петербург, ул. Кирочная, д. 41



Контакты: Гаранина Анна Эдуардовна,
[anna.garanina.90\@mail.ru](mailto:anna.garanina.90@mail.ru)

## Резюме

## Введение

Рак молочной железы (РМЖ) относится к серьезной глобальной проблеме
здравоохранения: это наиболее часто диагностируемый вид рака в мире [@wilkinson2022]. В структуре раннего скрининга молочной железы
имеет важное значение проблематика плотности молочной железы [@boyd2013; @lee2012].
Новая технология 3D ABUS позволяет получать большие трехмерные объемы,
и имеет преимущества для организации скрининга РМЖ [@zanotel2017].

Исследование технологии 3D ABUS является перспективным направлением
улучшения алгоритмов и подходов при скрининге молочной железы.

## Цель исследования

Провести сравнительный анализ диагностической эффективности, именно
чувствительности, специфичности и точности УЗИ в B-режиме,
автоматизированного объемного сканирования молочных желез (ABUS), и
маммографического скрининга у женщин в возрастной группе 40 лет и старше
лет с неоднородной и высокой плотностью тканей молочной железы.

## Материалы и методы

С февраля 2019 по май 2023 года проводилось ретро-проспективное
наблюдательное исследование, в котором рассматривались диагностические
аспекты раннней диагностики рака молочной железы с реди женщин в
возрасте 40 лет и старше.Всего в исследование вошло 1283 пациентов.  
В группу A вошло 628 пациенток, в то время как в группу B 655 пациентов. 
Пациентки попавшие в группу B проходили 2D-УЗИ с определением категории BiRads и 3D-УЗИ. Пациентки попавшие в группу B проходили только 2D-УЗИ. Все пациентки проходили диагностическую маммографию.
Проводилось определение чувствительности, спецефичности, точности, положительной прогностической ценности и отрицательной прогностической ценности

## Результаты исследования

По результатам выполнения УЗИ был поставлен дигноз злокачественного
образования в группе A в 7.64% (48), а в группе B в 22.29% (146)
По результатам выполнения гистологическкого исследования был поставлен
дигноз злокачественного образования в группе A в 7.64% (48) и и в группе
B в 22.29% (146).
Метод ММГ показал ППЦ 0.89, ОПЦ 0.93, чувствительность 0.53, специфичность 0.99, отбалансированную точность 0.76. Метод 2D-УЗИ показал ППЦ 0.8, ОПЦ 0.98, чувствительность 0.9, специфичность 0.97, отбалансированную точность 0.93 и площадь под кривой предсказательной модели 0.968. 3D-УЗИ показал ППЦ 0.97, ОПЦ 0.97, чувствительность 0.9, специфичность 0.99, отбалансированную точность 0.94 и площадь под кривой предсказательной модели 0.98.


## Выводы

По результатам нашего исследования диагностическая эффективность, а
именно чувствительности, специфичности и точности автоматизированного
объемного сканирования молочных желез (ABUS) не хуже УЗИ в B-режиме и
маммографического скрининга у женщин возрастной группы 40 лет и старше.
3D-ABUS представляется многообещающим дополнительным методом к
программам скрининга.

## Список литературы
