---
title: "Tesis_3_algo"
author: "AndreyPovaliy"
date: "2024-02-13"
output: word_document
bibliography: references3.bib
csl: american-medical-association-brackets.csl
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Роль автоматизированного 3d УЗИ при скрининге новобразований молочной железы

Гаранина Анна Эдуардовна – аспирант кафедры лучевой диагностики ФГБОУ ВО
“Северо-Западный государственный Медицинский университет им.
И.И.Мечникова”, Врач ультразвуковой диагностики, Санкт-Петербург,
Российская Федерация. 191015, Российская Федерация, г. Санкт-Петербург,
ул. Кирочная, д. 41

e-mail:
[anna.garanina.90\@mail.ru](mailto:anna.garanina.90@mail.ru){.email}
телефон: +7 921 554-97-03 SPIN-код: 8668-3521 ORCID:
<https://orcid.org/0009-0001-8193-6657>

Холин Александр Васильевич - доктор медицинских наук, профессор
заведующий кафедрой лучевой диагностики ФГБОУ ВО “Северо-Западный
государственный Медицинский университет им. И.И.Мечникова”. 191015,
Российская Федерация, г. Санкт-Петербург, ул. Кирочная, д. 41

e-mail: [holin1959\@list.ru](mailto:holin1959@list.ru){.email}.
SPIN-код: 9791-8550 ORCID: <https://orcid.org/0000-0001-8227-1530>

Рак молочной железы (РМЖ) представляет собой серьезную угрозу [@guo2018;
@mann2019]. Поэтому вопрос о ранней диагностике рака является
чрезвычайно актуальной темой обсуждения. УЗИ в настоящее время является
наиболее важным методом визуализации для клинической диагностики
заболеваний молочной железы (МЖ) [@rix2021; @kaur2022; @suter2020].
Автоматическое ультразвуковое исследование МЖ (3D УЗИ) стало важным
инструментом в диагностике РМЖ [@garanina2023]. Считается, что 3D УЗИ
обладает высокой воспроизводимостью, низкой зависимостью от оператора,
меньшими затратами времени на получение изображений, автоматической
трехмерной реконструкцией всей МЖ, уникальным коронарным срезом и
относительно широким полем наблюдения. Однако на сегодняшний день метод
3D УЗИ обладает схожими показаниями с 2d УЗИ, но имеет иные временные
возможности, что создает потенциал для оптимизации скрининга.

## The role of automated 3d ultrasound in screening for breast tumors

Anna Eduardovna Garanina – postgraduate of the Department of Radiation
Diagnostics North-Western State Medical University named after I.I.
Mechnikov, Saint Petersburg, Russian Federation 191015, 41 Kirochnaya
str., Saint Petersburg, Russian Federation e-mail:
[anna.garanina.90\@mail.ru](mailto:anna.garanina.90@mail.ru){.email}
phone: +7 921 554-97-03 SPIN-сode: 8668-3521 ORCID:
<https://orcid.org/0009-0001-8193-6657>

Kholin Alexander Vasilievich - Dr. of Sci. (Med.), Professor, Professor,
Head of the Department of Radiation Diagnostics North-Western State
Medical University named after I.I. Mechnikov, Saint Petersburg, Russian
Federation 191015, 41 Kirochnaya str., Saint Petersburg, Russian
Federation e-mail:
[holin1959\@list.ru](mailto:holin1959@list.ru){.email}. SPIN-code:
9791-8550 ORCID: <https://orcid.org/0000-0001-8227-1530>

Breast cancer is a serious threat [@guo2018; @mann2019]. Therefore, the
issue of early diagnosis of cancer is an extremely relevant topic of
discussion. Ultrasound is currently the most important imaging modality
for the clinical diagnosis of breast disease [@rix2021; @kaur2022;
@suter2020]. Automated ultrasound examination of the breast (3D
ultrasound) has become an important tool in the diagnosis of breast
cancer [@garanina2023]. It is believed that 3D ultrasound has high
reproducibility, low dependence on the operator, less time spent on
obtaining images, automatic three-dimensional reconstruction of the
entire breast, a unique coronary section and a relatively wide field of
observation. However, today the 3D ultrasound method has similar
indications to 2D ultrasound, but has different time capabilities, which
creates the potential for optimizing screening.

**Цель.** Определить наиболее значимые факторы для переопределения
алгоритма маршрутизации пациента с учетом использования 3D УЗИ.

**Материалы и методы.** Ретро-проспективное наблюдательное исследование.
Исследование проводилось с февраля 2019 по май 2023 года. Все пациентки
были разделены на 2 независимые друг от друга выборки по принципу
возраста: выборка пациенток с возрастом до 40 лет и выборка пациенток с
возрастом от 40 лет включительно. В выборку до 40 лет вошло 1511
пациенток и 628 был выполнен 3D УЗИ. В выборку 40 лет и старше вошло
1283 пациенток и 655 был выполнен 3D УЗИ. Все пациенткам проводился
скрининг с использованием не только 2D УЗИ. По результатам 2D УЗИ были
выставлены категории BIRADS. Для 1 и 2 категории было рекомендовано
дальнейшее наблюдение. При установке категории BIRADS 3 было
рекомендовано проведение магнитно-резонансная томография с контрастным
усилением для уточнения. При категории BIRADS 4 и BIRADS 5 проводилась
CORE-биопсия или стереотаксическая биопсия или пункционная биопсия.
Проводилось определение наиболее значимых факторов для проведения
биопсии.

**Результаты.** Были выявлены наиболее значимые факторы и на их
основании скрининг с 3D УЗИ в выборке до 40 лет не показан в 4.04%
(61/1511случаев)[95% ДИ 0.03;0.05] и в 95.96% (1450/1511случаев)[95% ДИ
0.95;0.97] его можно использовать. Представленная модель в выборке до 40
лет сработала корректно в 99.21% (1499/1511случаев) [95% ДИ 0.99;1] и в
0.79% (12/1511случаев) [95% ДИ 0;0.01] предсказание можно отнести к
неверному, а именно ложноположительные результаты. В то время как
скрининг с 3D УЗИ в выборке 40 лет и старше не показан в 15.74%
(202/1283случаев)[95% ДИ 0.14;0.18], в 84.26% (1081/1283случаев)[95% ДИ
0.82;0.86] исследование целесобразно. Представленная модель сработала
корректно в 97.12% (1246/1283 случаев) [95% ДИ 0.96;0.98] и в 2.88%
(37/1283случаев) [95% ДИ 0.02;0.04] нет. Среди 37 случаев неверного
предсказания было 4 случая ложноотрицательных результата, и эти пациенты
буду направлены на повторное исследование к специалисту УЗИ для
проведения трепан биопсии, 33 случая квалифицированы как
ложноположительные.

**Выводы.** Можно с уверенностью сказать, что 3D УЗИ не уступает по
своим возможностям традиционному методу УЗИ в ранней диагностике
новообразований МЖ как у пациенток до 40 лет, так у пациенток 40 лет и
старше. Метод диагностики 3D УЗИ является не замещающим, а дополняющим
традиционную УЗИ диагностику в структуре ранней диагностики и может
поспособствовать оптимизации организации потока пациенток.  
