# ВВЕДЕНИЕ {.unnumbered}

## Актуальность исследования

Рак молочных желез (РМЖ[^1]) относится к серьезной глобальной проблеме здравоохранения: это наиболее часто диагностируемый вид рака в мире.
Количество случаев РМЖ, зарегистрированных в 2020 году, составило 2,26 миллиона [@wilkinson2022], причем более половины из них зарегистрированы в менее развитых регионах мира [@sung2021].
Наблюдаемое преимущество в выживаемости пациентов с диагностированным РМЖ в более развитых странах в значительной степени может быть связано с сочетанием стратегий раннего выявления, доступа к ранней диагностике и эффективным методам лечения.
Напротив, отсроченное проявление чаще встречается в менее развитых регионах мира, где более половины случаев РМЖ относятся местно-распространенному или метастатическому.
РМЖ представляет наиболее распространенный вид рака, диагностируемый ежегодно среди женщин (более 1 из 10 новых ежегодных случаев РМЖ).
В соответствии с данными всемирной организации здравоохранения (ВОЗ[^2]) и глобальной онкологической обсерватории (The Global Cancer Observatory - GCO[^3]), РМЖ — самое распространенное онкологическое заболевание у женщин с частотой выявления 46,4 на 100 ты
с. женщин в мире и 53,6 на 100 ты
с. в Российской Федерации (РФ
[^4]). РМЖ также является основной причиной смерти от ЗНО среди женщин; смертность от РМЖ в мире составляет 13,0 на 100 ты
с. женщин, в РФ — 15,1 на 100 тыс [@kaprinzlokachestvennyye2017; @kaprinsostoyaniye2020; @kaprinsostoyaniye2020; @kushuninavyyavleniye2019; @mahvi2018]. Большинством руководств маммографический скрининг был рекомендован женщинам в возрасте 40–74 лет [@hamashima2016; @qaseem2019; @ren2022; @siu2016; @urban2017], женщинам в возрасте 50–69 лет проведение скрининга было обязательным [@migowski2018; @ren2022; @schunemann2019; @wockel2018]. Определение плотности молочных желез (МЖ[^5]) помогает в более точной стратификации риска развития РМЖ (прогностической и профилактической), помогает определиться с необходимым объемом дополнительных диагностических методик исследования плотной МЖ, как независимого фактора риска развития Р
МЖ. Американская коллегия радиологов (ACR[^6]) в 3-ем издании cистемы визуализации молочной железы - отчетность и данные (Breast imaging-Reporting and Data System - BI-RADS[^7] описывает плотность МЖ с точки зрения четырех категорий общей плотности. Первоначально эти категории были простыми описательными терминами («жировая», «рассеянная плотность», «гетерогенно плотная» и «чрезвычайно плотная») [@dorsi2018]. Литературные данные подтверждают факт того, что женщины с плотной МЖ типа D имеют четырех-шестикратное увеличение риска по сравнению с женщинами с плотностью МЖ типа A [@boyd2013; @lee2012]. Именно плотность МЖ в общей популяции чаще по сравнению с другими факторами такими как возраст, генетические мутации BRCA[^8] 1 и BRCA2, является самым сильным предиктором развити
я РМЖ. В некоторых исследованиях было высказано предположение, что только показатель плотности МЖ вносит значительный вклад в риск развития РМЖ на популяционном уровне, составляя 16% всех диагностированных РМЖ [@bae2014; @boyd2007; @boyd2011; @fasching2006]. По мнению большинства исследователей интервальный рак, то есть выявленный в промежутке между запланированными скрининговыми маммограммами, в 13-31 раз более вероятен в МЖ с плотностью типа D, чем в МЖ с плотностью типа А [@boyd2007; @ciatto2004; @posso2019; @strand2019]. Плотность МЖ также является биомаркером для прогнозирования ответа на неоадъювантную химиоте
рапию. Skarpi
ng, I. и
соавт. в 2
019 г. в своем исследовании показали, что женщины в пременопаузе с высокой маммографической плотностью плохо реагируют на неоадъювантную химиотерапию [@skarping2019]. Маммографическая плотность МЖ длительное время была предметом дискуссий между учеными и практическими докт
орами. В частности, активно обсуждался вопрос необходимости информирования женщин о наличии у них высокой плотности МЖ [@almousa2014; @machida2015; @tossasmilligan2019]. Большинство авторов сходятся во мнении, что женщины должны быть проинформированы в связи с тем, что плотная ткань МЖ может: 1) скрывать опухоли на маммограмме, 2) повышать риск развития РМЖ и 3) требовать проведения дополнительных методов исследований, таких как УЗИ и магнитно-резонансной томографии (МРТ) [@tossasmilligan2019]. Таким образом в настоящее время требуется изучение возможностей новых методов скрининга МЖ не столь зависимых от плот
ности.

[^1]: РМЖ - рак молочных желез

[^2]: ВОЗ - всемирная организация здравоохранения

[^3]: GCO - The Global Cancer Observatory (глобальная онкологическая обсерватория)

[^4]: РФ - Российская Федерация

[^5]: МЖ - молочная железа

[^6]: ACR - American College of Radiology (американская коллегия радиологов)

[^7]: BI-RADS - Breast imaging-Reporting and Data System (cистема визуализации молочной железы - отчетность и данные)

[^8]: BRCA - BReast CAncer gene (ген рака молочной железы)

## Степень разработанности проблемы

Развитие автоматизированного объемного ультразвукового сканирования (3D УЗИ[^9]) является одним из наиболее перспективных направлений, который позволяет получить в среднем за 3 сканирования (коронарная, сагиттальная и аксиальнаяплоскости) изображение всей МЖ.

[^9]: 3D УЗИ - автоматизированное объемное ультразвуковое сканирование (от англ. ABUS - Automated Breast Ultrasound - Автоматизированное УЗИ молочной железы)

Кроме того, разработано специальное программное обеспечение для 3D УЗИ с целью автоматизированного обнаружения патологических образований, система автоматизированного проектирования (САПР[^10]), которое получило одобрение управления по санитарному надзору за качеством пищевых продуктов и медикаментов США [@jiang2018; @vourtsis2018].

[^10]: САПР - система автоматизированного проектирования

Анализ различных исследований показал более высокие или равные результаты обнаружения поражений МЖ с помощью 3D УЗИ по сравнению с 2D УЗИ[^11].
Показатели обнаружения с помощью 3D УЗИ варьируют от 84,8% до 100%, тогда как соответствующие показатели для ультразвукового метода- от 60,6% до 100% [@kim2013; @lin2012; @vourtsis2019; @wang2012; @xiao2015].

[^11]: 2D УЗИ - традиционное ультразвуковое исследование

В литературе также встречаются работы, посвященные дифференциации злокачественных и доброкачественных образований МЖ с помощью 3D УЗИ [@chouautomated2007; @golatta2013; @golatta2014; @kotsianoshermle2009].

3D УЗИ, благодаря хорошей визуализации МЖ также является новым методом оперативного планирования [@grady2010].
Размер поражения, определенный с помощью 3D УЗИ, хорошо коррелирует с результатами МРТ [@schmachtenberg2017] и гистопатологическими изменениями [@chang2015].

Коронарная плоскость имеет особое значение для хирургического планирования из-за лучшей визуализации сегментарного доступа и схожей ориентации при позиционировании пациента во время операции [@amylobar2018].
3D УЗИ также позволяет визуализировать сателлитные очаги размером менее 1 см, что очень ценно в оценке многоочагового рака.

3D УЗИ может применяться при оценке результатов МРТ в качестве уточняющей методики [@girometti2017; @halshtokuse2015]: так, например, 3D УЗИ превзошел 2D УЗИ в качестве вторичного исследования после проведения МРТ МЖ, выявив дополнительные очаги [@kim2016].

В работах отечественных исследователей [@gazhonovavozmozhnosti2015] изучались возможности данной методики в определении типа строения МЖ среди женщин разных возрастных групп, имеющих различную патологию.
Полученные ими данные свидетельствовали и значительном увеличении специфичности данного метода (до 96%) у пациенток с типами плотности МЖ С и D, что может иметь важное значение при скрининге женщин данной категории [@gazhonovavozmozhnosti2015].

Была доказана добавленная ценность 3D УЗИ к маммографии (ММГ[^12]) при высокой плотности МЖ, где было показано повышение выявляемости РМЖ на 57% [@vourtsis2018].

[^12]: ММГ - маммография

Таким образом, 3D УЗИ— это технологический прогресс в области визуализации и скрининга МЖ с преимуществами стандартизации сканирований, лучшего обнаружения небольших поражений, особенно у женщин с повышенной плотностью МЖ, и сокращение времени сканирования.
Продолжаются интенсивные исследования новых разработок и дополнительных приложений для технологии 3D УЗИ.
Оценка плотности МЖ с помощью 3D УЗИ также является еще одним перспективным направлением.

Вместе с тем стоит сказать, что тактика скрининнга в разных возрастных группах, а именно в группе пациенток до 40 лет и группе пациенток 40 лет и старше, разная.
Не смотря на потенциальные преимущества 3D УЗИ четкого понимания диагностической эффективности, прогностической ценности, показаний к проведению исследования в разных возрастных группах, возможности визуализации кальцинатов нет и представленные вопросы требуют решения.

**Цель исследования** - повысить эффективность выявления образований молочных желез методом автоматизированного объемного ультразвукового сканирования.

## Задачи исследования

1.  Провести сравнительный анализ диагностической эффективности (чувствительности, специфичности и точности,) ультразвукового исследования в B- режиме и автоматизированного объемного ультразвукового сканирования МЖ (3D УЗИ), и комбинации этих методик у женщин в возрастной группе 30-39 лет с высокой плотностью тканей МЖ.

2.  Провести сравнительный анализ диагностической эффективности (чувствительности, специфичности и точности,) цифровой маммографии, ультразвукового исследования в B-режиме и автоматизированного объемного ультразвукового сканирования МЖ (3D УЗИ), и комбинации этих методик у женщин в возрастной группе старше 40 лет с высокой плотностью тканей МЖ.

3.  Определить прогностическую ценность методики автоматизированного объемного сканирования МЖ (3D УЗИ) в диагностике образований МЖ у женщин разных возрастных групп.

4.  Изучить возможность визуализации кальцинатов на 3D сонотомограммах и в 2D режиме ультразвукового исследования с использованием дополнительной функции Micro Pure.

5.  Оптимизировать алгоритмы обследования женщин с образованиями МЖ с использованием возможностей нового метода автоматизированного объемного ультразвукового сканирования.

## Научная новизна

Впервые определена диагностическая эффективность автоматизированного объемного ультразвукового сканирования молочных желез в сравнительном комплексном обследовании женщин разного возраста с использованием маммографии и ультразвукового исследования.

Впервые разработаны подробные классификаторы на основании текстовых данных анамнеза и описательной части заключений, которые легли в основу анализа предикативной модели метода автоматизированного объемного ультразвукового сканирования, позволившей выявить наиболее значимые факторы выявления злокачественного образования на преддиагностическом этапе

Впервые определено место метода автоматизированного объемного ультразвукового сканирования в лучевом алгоритме обследования женщин с плотной молочной железой в разных возрастных группах с учетом наиболее значимых преддиагностических факторов, наличие которых определяет маршрутизацию пациенток.

## Теоретическая и практическая значимость работы

1.  Применение результатов диссертации в программах скрининга рака молочных желез способствует выявлению большего количества новообразований на ранней стадии заболевания, что позволяет выбирать более щадящий вариант лечения, значительно влияет на качество и продолжительность жизни женщин, их психологическое состояние.
    Алгоритм обследования молочных желез дает возможность обследовать женщин с учетом типа строения молочных желез, назначать дополнительный скрининговый метод обследования пациенткам с плотной молочной железой при отрицательных результатах маммографии, выявлять образования молочных желез менее 1см, планировать операционный этап с учетом четкой локализации образований, отслеживать динамику при применении неоадъювантного лечения.

2.  Усовершенствованный алгоритм обследования молочных желез станет дополнительным инструментом в клинической практике гинекологов, онкологов, хирургов, рентгенологов, врачей ультразвуковой диагностики.

3.  Усовершенствованный алгоритм поможет оптмизировать процесс скрининга рака молочных желез, что значительно снизит нагрузку на медицинские учреждения поликлинического, амбулаторного профиля, онкологические диспансеры, консультативно- диагностические центры и затраты как для пациента, так и для системы здравоохранения Российской Федерации, а также станет перспективным направлением для развития систем скрининга в России.

## Методология и методы исследования

Исследование выполнено на кафедре лучевой диагностики ФГБОУ ВО «Северо-Западный государственный Медицинский университет им.
И.И.
Мечникова».

Клинический отбор пациентов проводился на базе одной медицинской клиники- АО «Поликлинический комплекс», состоящей из двух зданий -амбулаторно-поликлического комплекса и хирургического корпуса со стационаром.

Объектом исследования являлись пациенты с новообразованиями МЖ, регистрируемые при диагностике с использованием мануального ультразвукового исследования (2D УЗИ), маммографии (ММГ) и автоматизированного объемного УЗИ сканирования МЖ (ABUS, далее 3D УЗИ).

Предметом исследования являлись образования МЖ, выявленные методом автоматизированного объемного УЗИ сканирования МЖ, с последующим анализом наиболее важных факторов как на преддиагностическом этапе, так и при выполнении конкретного диагностического метода.

Дизайн исследования можно охарактеризовать ретро-проспективное клиническое исследование.
Протокол настоящего исследования был одобрен на заседании локального этического комитета СЗГМУ им.
Мечникова №9 от 12.10.2022 года.

В первой части настоящего исследования был проведен анализ профильной отечественной и зарубежной литературы для оценки состояния проблемы вывляемости РМЖ.

Вторая часть исследования состояла из клинических и диагностических исследований.
Все участники подписали форму информированного согласия.
На первом этапе всем пациентам проводили клинический осмотр, пальпацию, собрали информацию о социально-демографических данных и потенциальных факторах риска РМЖ.

На втором этапе пациентки были разделены на 2 независимые друг от друга выборки по принципу возраста: выборка пациенток моложе 40 лет и выборка пациенток старше 40 лет включительно.

Диагностический этап, включал в себя исследование с использованием метода 2D УЗИ, маммографии и 3D УЗИ в зависимости от группы распределения.
Производился сбор данных для последующего выявления наиболее значимых факторов, а также выявления эффективности изучаемых методов и оценки прогностической ценности метода.
Результаты выявленных изменений были классифицированы по BI-RADS по шести категориям: 0 = неполные данные, 1 = нормальные, 2 = доброкачественные, 3 =вероятно доброкачественные, 4 = подозрительные, 5 = с высокой степенью вероятности злокачественные, для 2D УЗИ, 3D УЗИ и ММГ.
Для категории BI-RADS3 проводилась магнитно-резонансная томография (МРТ) и/или динамическое наблюдение с коротким интервалом для выявления истинно отрицательных и ложноотрицательных результатов.
Женщинам, выявленные изменения которых, были отнесены к категории 4 или 5, проводилась трепан биопсия под уз-наведением или стереотаксическим наведением с последующей морфологической и при необходимости иммуногистохимической верификацией.

На последнем этапе выполнялась статистическая обработка данных.

## Основные положения, выносимые на защиту

1.  Диагностическая эффективность автоматизированного УЗИ МЖ у пациенток моложе 40 лет сопоставима по показателю специфичности и лучше по показателю точности, чувствительности и обладает более высокой прогностической ценностью по сравнению с ультразвуковым исследованием в 2D режиме.

2.  Диагностическая эффективность автоматизированного 3D-УЗИ МЖ у пациенток 40 лет и старше сопоставима по показателю чувствительности и лучше по показателю точности, специфичности и обладает высокой прогностической ценностью по сравнению с ультразвуковым исследованием в 2D режиме.

3.  Предлагаемый усовершенствованный алгоритм определяет место 3D УЗИ в структуре скрининга рака МЖ и потенциально может снизить нагрузку на врачей ультразвуковой диагностики и сократить время на проведение исследования.

## Степень достоверности и апробация диссертационной работы

Достоверность полученных результатов определяется достаточным количеством набранного материала для решения поставленной цели и задач исследования.
Выбраны адекватные статистические методы обработки данных.
Объем проведенной работы достаточен для решения поставленных задач, цели исследования и обоснования выводов, и клинических рекомендаций.
Основные положения настоящего диссертационного исследования были доложены на Невском радиологическом форуме (Сборник тезисов XV международного конгресса, Санкт-Петербург, 12–13 апреля 2024 года), на Всероссийском конгрессе ординаторов медицинских вузов «Научно-практическая подготовка ординаторов(СПб, 2024), на конференции «Fundamental аnd applied sciences today XXXIII”-ХXXIII международной научно-практической конференции «Фундаментальные и прикладные науки сегодня» (Bengaluru, Karnataka, India, 2024).

## Внедрение результатов работы в практику

Результаты диссертационной работы внедрены автором в практическую деятельность отделения ультразвуковой диагностики АО «Поликлинический комплекс» клиники СМТ, результаты диссертационного исследования внедрены в научную, и образовательную деятельность ФГБОУ ВО «СЗГМУ им.
И.И.
Мечникова» Минздрава России.

## Личный вклад соискателя

Автор настоящего исследования определил цель и задачи, разработал методологические подходы и дизайн исследования совместно с научным руководителем.
Статистическая обработка полученных результатов была проведена самостоятельно.
Автор настоящей диссертации лично участвовал в сборе и анализе литературных данных; оценке ретро- и проспективных результатов и изучению документации; разработке насадки на датчик аппарата ультразвукового исследования для диагностики МЖ; непосредственное планирование и организация исследований 2D и 3D УЗИ; подготовке материалов к публикации; участии в написании статей; подготовке докладов на научных конференциях по теме работы.

## Публикации

По теме диссертации опубликовано 11 печатных работ, в том числе 6 статей в рецензируемых научных журналах, входящих в список рекомендованных ВАК РФ для научных публикаций диссертантов, выпущено 1 наглядное учебное пособие по теме диссертации и получен 1 патент по теме диссертации.

## Структура и объем диссертации

Диссертация изложена на 212 страницах машинописного текста, иллюстрирована 33 рисунками, содержит 29 таблиц; состоит из введения, обзора литературы, характеристики исследуемых пациентов и описания методов исследования, а также 5 глав собственных исследований, заключения, выводов, практических рекомендаций и списка литературы, содержащего 185 источников, из них 27 отечественных и 158 иностранных.