---
title: "Jun_Accur_3"
author: "Andrey Povaliy"
date: "2023-09-04"
output: word_document
bibliography: references1.bib
csl: american-medical-association-brackets.csl
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Диагностическая эффективность автоматизированного УЗИ всей молочной железы при раке молочной железы у пациенток до 40 лет.

## Введение

Рак молочной железы является наиболее распространенным раком среди
женщин во всем мире [@shapira2017; @kocarnik2022cancer]. В Российской
Федерации ежегодно регистрируется более 70 тысяч новых случаев рака
молочной железы (70 208 в 2021 году), в том числе 495 случаев среди
мужского населения и ежегодно умирает более 20 тысяч пациенток с раком
молочной железы (20 620 в 2021 году), в том числе 140 мужчин
[@мерабишвили2022состояние; @мерабишвили2023состояние]. Женщины в
возрасте \<40 лет обычно имеют эквивалентный риск до или выше, чем у
женщины среднего риска в возрасте 40 лет. Раннее выявление снижает
смертность среди женщин с раком молочной железы [@monticciolo2018].

## Цель исследования

Провести сравнительный анализ диагностической эффективности УЗИ в
B-режиме и автоматизированного объемного сканирования молочных желез
(ABUS), и комбинации этих методик у женщин в возрастной группе до 39 лет
с высокой плотностью тканей молочной железы.

## Материалы и методы

Было проведено ретро-проспективное наблюдательное исследование. С
февраля 2019 по май 2023 года было исследовано 1511 пациенток с
возрастом до 40 лет. Пациенки были разделены на две группы A и B. В
группу A вошло 724 пациенток и в это группе скрининг проводился с
использовонием не только 2d УЗИ, но и 3в УЗИ сканирования молочных желез
(исследуемая группа). В группу B вошло 787 пациенток и в этой группе
скрининг проводился только с 2d УЗИ (котнтрольная группа). По
результатам 2d УЗИ были выставлены категории BiRads. Для 1 и 2 категории
было рекомендовано дальнейшее наблюдение. При усановке категории BiRads
3 было рекомендовано проведение магнитно-резонансная томография с
контрастным усилением для уточнения. При категории BiRads 4 и BiRads 5
проводилась core биопсия или стереотаксическая биопсия или пункционная
биопсия. Проводилось определение чувствительности, спецефичности,
точности, положительной прогностической ценности и отрицательной
прогностической ценности.

## Результаты исследования

По результатам выполнения УЗИ был поставлен дигноз злокачественного
образования в группе A в 1.91% (15), в группе B в 6.49% (47). При
выполнении ABUS был поставлен дигноз злокачественного образования в
группе A в 1.91% (15) в группе B в 6.49% (47). По результатам выполнения
гистологическкого исследования был поставлен дигноз злокачественного
образования в группе A в 1.91% (15), а в группе B в 6.49% (47). Метод
УЗИ в группе А показал чувствительность 0.8, специфичность 1,
отбалансированную точность 0.9 и площадь под кривой предсказательной
модели 0.947, УЗИ в группе B 0.89, 0.98, 0.94 и 0.903 соответственно,
УЗИ по всей выборке 0.87, 0.99, 0.93 и 0.916 соответственно. Метод ABUS
в группе B показал чувствительность 0.95, специфичность 0.99 и
отбалансированную точность 0.97 и площадь под кривой предсказательной
модели 0.968.

## Выводы

Согласно проведенному нами исследованию диагностическая эффективность
автоматизированного УЗИ всей молочной железы при раке молочной железы у
пациенток до 40 лет достоверно не хуже проведения классического УЗИ
исследования.

## Список литературы
